### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by Anish8659** [Differentunic/Montserrat-Alt1#4]
Is this font free to use for commercial uses?

**Comment by Differentunic** [comment]
Yes, you can. I would appreciate a reference that the font was created by me, and please follow the SIL Open Font Liscense 1.1.

Thanks!

--------------------------------------------------------
Differentunic/Montserrat-Alt1 is licensed under the
SIL Open Font License 1.1

The Open Font License (OFL) is maintained by SIL International. It attempts to be a compromise between the values of the free software and typeface design communities. It is used for almost all open source font projects, including those by Adobe, Google and Mozilla.

Permissions:
- Private use
- Commercial use
- Modification
- Distribution

Limitations:
- Liability
- Warranty
- 
Conditions:
- License and copyright notice
- Same license

**Comment by Differentunic** [comment]
This issue has closed because the question has been answered.

Still having problems? re-open this issue, and describe what the problem is.
